trigger:
- main

pool:
  name: 'FarzamAgent'

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'

- task: DeleteFiles@1
  inputs:
    SourceFolder: 'C:\Farzamte\ui'
    Contents: '**/*'
  displayName: 'Delete old files'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    contents: '**/*'
    targetFolder: 'C:\Farzamte\ui'
  displayName: 'Copy files to destination'

- task: CopyFiles@2
  inputs:
    sourceFolder: 'C:\Farzamte\ui_need'
    contents: '**/*'
    targetFolder: 'C:\Farzamte\ui'
  displayName: 'Copy additional files to destination'
